In [1]:
import numpy as np

In [2]:
# creating array from list
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
# diamension of the array
print(arr.ndim)

2


In [4]:
#shape of the copy
np.shape(arr)

(2, 4)

In [5]:
#type 
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr.data)

# Statistical Functions

In [7]:
"""In 2-D Arrays:
axis = 0 (Column) 
axis = 1 (Row)"""

'In 2-D Arrays:\naxis = 0 (Column) \naxis = 1 (Row)'

In [8]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x, "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [9]:
x.dtype

dtype('int32')

In [10]:
x.itemsize

4

In [11]:
x.size

9

In [12]:
x.shape

(3, 3)

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float32)
print(a, "\n")
print(a.dtype, "\n")
print(a.itemsize)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

float32 

4


In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)
print(a, "\n")
print(a.dtype, "\n")
print(a.itemsize)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

float64 

8


In [15]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.complex64)
y = np.array([[11,12,13],[14,15,16],[17,18,19]], dtype=np.complex128)
print(x, "\n")
print(x.dtype, "\n")
print(x.itemsize, "\n")
print(y, "\n")
print(y.dtype, "\n")
print(y.itemsize, "\n")

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]] 

complex64 

8 

[[11.+0.j 12.+0.j 13.+0.j]
 [14.+0.j 15.+0.j 16.+0.j]
 [17.+0.j 18.+0.j 19.+0.j]] 

complex128 

16 



In [16]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x, "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [17]:
# sum of an array
print(np.sum(x))

45


In [18]:
# sum value along a specified axis
print(x, "\n")
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[12 15 18]
[ 6 15 24]


In [19]:
# minimum value
print(x, "\n")
print(np.min(x))
print(np.min(x, axis=0))
print(np.min(x, axis=1))
print(type(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

1
[1 2 3]
[1 4 7]
<class 'numpy.ndarray'>


In [20]:
# maximum value
print(x, "\n")
print(np.max(x))
print(np.max(x, axis=0))
print(np.max(x, axis=1))
print(type(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

9
[7 8 9]
[3 6 9]
<class 'numpy.ndarray'>


In [21]:
# mean
print(x, "\n")
print(np.mean(x))
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))
print(type(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

5.0
[4. 5. 6.]
[2. 5. 8.]
<class 'numpy.ndarray'>


In [22]:
# standard deviation
print(x, "\n")
print(np.std(x))
print(np.std(x,axis=0))
print(np.std(x,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [23]:
# variance
print(x, "\n")
print(np.var(x))
print(np.var(x,axis=0))
print(np.var(x,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

6.666666666666667
[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]


In [24]:
# weighted average
print(np.average(x))

5.0


In [25]:
c = np.array([1,2,3, 4,5,6, 7,8,9])
print(c)

[1 2 3 4 5 6 7 8 9]


In [26]:
weight = np.array([0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25])
print(weight)

[0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25]


In [27]:
print(np.average(c, weights=weight))

5.0


In [28]:
# percentile
print(c, "\n")
print(np.percentile(c,5,0))
print(np.percentile(c,8,0))
print(np.percentile(x,5,1))
print(np.percentile(x,5,0))
print(np.percentile(x,4,1))
print(np.percentile(x,4,0))

[1 2 3 4 5 6 7 8 9] 

1.4
1.6400000000000001
[1.1 4.1 7.1]
[1.3 2.3 3.3]
[1.08 4.08 7.08]
[1.24 2.24 3.24]


In [29]:
# peak to peak
print(x, "\n")
print(c, "\n")

print(np.ptp(c,0))
print(np.ptp(x,0))
print(np.ptp(x,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9] 

8
[6 6 6]
[2 2 2]


In [30]:
print(x,"\n")
print(x.shape,"\n")
print(x.reshape(1,9),"\n")
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

(3, 3) 

[[1 2 3 4 5 6 7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Slicing

In [31]:
e = [5,10,15,20,25,30,35]
print([e[0:4]],"\n")
print(e[-1])

[[5, 10, 15, 20]] 

35


In [32]:
# 2-D Array
l = np.array([[5,10,15,20],[25,30,35,40],[45,50,55,60]])
print(l,"\n")
print(l[0,3],"\n")
print(l[1,2],"\n")
print(l[2,3],"\n")
print(l[0,1],"\n")
print(l[0:2,1],"\n")
print(l[-1],"\n")
print(l[-1,0:2],"\n")

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]] 

20 

35 

60 

10 

[10 30] 

[45 50 55 60] 

[45 50] 

